// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADrYDh2O6Ed3EcOVgBzqT22Fm0rlBsK-k',
    appId: '1:917477991237:web:6ee889b89f4bf31e96142c',
    messagingSenderId: '917477991237',
    projectId: 'spectrasense-2533e',
    authDomain: 'spectrasense-2533e.firebaseapp.com',
    storageBucket: 'spectrasense-2533e.firebasestorage.app',
    measurementId: 'G-3G4LZR6JMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhJSMbW_PdEVdnHyM6CPSKef30E6TZCUQ',
    appId: '1:917477991237:android:0c5d1f75cb8a0c1396142c',
    messagingSenderId: '917477991237',
    projectId: 'spectrasense-2533e',
    storageBucket: 'spectrasense-2533e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy1co5ampMM3eaGpgGSZ9RNbNVo7K1fvI',
    appId: '1:917477991237:ios:2e6f05719c26500496142c',
    messagingSenderId: '917477991237',
    projectId: 'spectrasense-2533e',
    storageBucket: 'spectrasense-2533e.firebasestorage.app',
    iosBundleId: 'com.SpectraSense',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy1co5ampMM3eaGpgGSZ9RNbNVo7K1fvI',
    appId: '1:917477991237:ios:e574a867f351a32796142c',
    messagingSenderId: '917477991237',
    projectId: 'spectrasense-2533e',
    storageBucket: 'spectrasense-2533e.firebasestorage.app',
    iosBundleId: 'com.brigidcancercare.brigid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADrYDh2O6Ed3EcOVgBzqT22Fm0rlBsK-k',
    appId: '1:917477991237:web:6c40c13d86163fac96142c',
    messagingSenderId: '917477991237',
    projectId: 'spectrasense-2533e',
    authDomain: 'spectrasense-2533e.firebaseapp.com',
    storageBucket: 'spectrasense-2533e.firebasestorage.app',
    measurementId: 'G-8JZJZ06SYY',
  );
}
