// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD10NEqAuovs3ZrsngJsnLKt5gq8yMbbA4',
    appId: '1:223345032927:web:989e8dfb0a57f36620f36a',
    messagingSenderId: '223345032927',
    projectId: 'spectrasense',
    authDomain: 'spectrasense.firebaseapp.com',
    storageBucket: 'spectrasense.firebasestorage.app',
    measurementId: 'G-17ZKP6MJNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNMBybHUVUF8fDoD6y4BnBlWnIOQmVxB4',
    appId: '1:223345032927:android:e016aebf5eeba0fa20f36a',
    messagingSenderId: '223345032927',
    projectId: 'spectrasense',
    storageBucket: 'spectrasense.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUyJBeVtTQeDWXBsezEXgEm1Utj_G8Lq8',
    appId: '1:223345032927:ios:35c94be8d28a0fee20f36a',
    messagingSenderId: '223345032927',
    projectId: 'spectrasense',
    storageBucket: 'spectrasense.firebasestorage.app',
    iosBundleId: 'com.spectrasense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUyJBeVtTQeDWXBsezEXgEm1Utj_G8Lq8',
    appId: '1:223345032927:ios:35c94be8d28a0fee20f36a',
    messagingSenderId: '223345032927',
    projectId: 'spectrasense',
    storageBucket: 'spectrasense.firebasestorage.app',
    iosBundleId: 'com.spectrasense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD10NEqAuovs3ZrsngJsnLKt5gq8yMbbA4',
    appId: '1:223345032927:web:6d44b1f8b454c0c420f36a',
    messagingSenderId: '223345032927',
    projectId: 'spectrasense',
    authDomain: 'spectrasense.firebaseapp.com',
    storageBucket: 'spectrasense.firebasestorage.app',
    measurementId: 'G-4N8SHSZWN4',
  );
}
